import subprocess  # Used for interacting with system shell commands
from langchain_core.messages import ToolMessage  # Message type for messages generated by tools

def execute_command(command: str, capture_output: bool = False) -> str:
    """
    Executes a shell command and returns its output.
    
    Parameters:
      command (str): The shell command to be executed.
      capture_output (bool): If True, captures and returns the output; otherwise, discards it.
    
    Returns:
      str: The resulting standard output, stripped of extra whitespace.
    """
    # Run the command with a timeout and proper stdout/stderr redirection
    result = subprocess.run(
        command,
        shell=True,
        stdout=subprocess.PIPE if capture_output else subprocess.DEVNULL,
        text=True,
        timeout=60,  # Limit command execution time
        stderr=subprocess.PIPE
    )
    return result.stdout.strip()  # Return the clean output

def handle_tool_calls(history):
    """
    Checks if the last message in the history is a ToolMessage and updates the previous message metadata.
    
    Parameters:
      history (list): A list of conversation message objects.
      
    Returns:
      list: The updated conversation history.
    """
    message = history[-1]  # Get the most recent message
    
    # If the latest message is generated by a tool and there is at least one previous message
    if isinstance(message, ToolMessage) and len(history) > 1:
        previous_message = history[-2]  # Get the message before the tool response
        
        # If the previous message had tool_calls metadata, reset it to avoid duplicate processing
        if hasattr(previous_message, "tool_calls") and previous_message.tool_calls:
            previous_message.response_metadata = {}  # Clear old response metadata
            previous_message.usage_metadata = {}     # Clear old usage metadata
            print("Updated tool_calls parameters for previous message")  # Debug log message
    
    return history  # Return the possibly updated history
